### ISSUE TITLE
Create the Owner Profile Screen

### ISSUE THREAD

**Issue by Siddheshuncodes** [ArohiSoftwares/tiffin-management-system#5]
We need to implement the Profile Screen for owners.

Requirements:

The screen should display the owner's profile information, such as:
Name
Email
Contact Number
Include an option to edit the profile.
Ensure the layout is appealing and in line with the app’s design.
Expected Outcome:

A functional profile screen that allows owners to view and edit their information.

**Comment by aayushman-singh** [comment]
Hey @Siddheshuncodes , I've begun working on this issue. Can it be assigned to me?
